export default {
  "react-hooks/exhaustive-deps": 0,
  "react-hooks/rules-of-hooks": 0,
  "react-hooks/component-hook-factories": 0,
  "react-hooks/config": 2,
  "react-hooks/error-boundaries": 0,
  "react-hooks/gating": 2,
  "react-hooks/globals": 2,
  "react-hooks/immutability": 0,
  "react-hooks/incompatible-library": 2,
  "react-hooks/preserve-manual-memoization": 2,
  "react-hooks/purity": 0,
  "react-hooks/refs": 0,
  "react-hooks/set-state-in-effect": 0,
  "react-hooks/set-state-in-render": 0,
  "react-hooks/static-components": 0,
  "react-hooks/unsupported-syntax": 0,
  "react-hooks/use-memo": 0,
};
