import preset from "./preset.js";

export default {
  "class-methods-use-this": 0,
  "default-param-last": 0,
  "dot-notation": 0,
  "init-declarations": 0,
  "max-params": 0,
  "no-array-constructor": 0,
  "no-dupe-class-members": 0,
  "no-empty-function": 0,
  "no-implied-eval": 0,
  "no-loop-func": 0,
  "no-magic-numbers": 0,
  "no-redeclare": 0,
  "no-restricted-imports": 0,
  "no-shadow": 0,
  "no-unused-expressions": 0,
  "no-unused-vars": 0,
  "no-use-before-define": 0,
  "no-useless-constructor": 0,
  "prefer-destructuring": 0,
  "prefer-promise-reject-errors": 0,
  "require-await": 0,

  "ts/adjacent-overload-signatures": 2,
  "ts/array-type": 2,
  "ts/await-thenable": 0,
  "ts/ban-ts-comment": 0,
  "ts/ban-tslint-comment": 0,
  "ts/class-literal-property-style": [2, "fields"],
  "ts/class-methods-use-this": 0,
  "ts/consistent-generic-constructors": 0,
  "ts/consistent-indexed-object-style": 0,
  "ts/consistent-type-assertions": 2,
  "ts/consistent-type-definitions": [2, "interface"],
  "ts/consistent-type-exports": 2,
  "ts/consistent-type-imports": [2, { fixStyle: "inline-type-imports" }],
  "ts/default-param-last": 2,
  "ts/dot-notation": 0,
  "ts/explicit-function-return-type": 0,
  "ts/explicit-member-accessibility": 2,
  "ts/explicit-module-boundary-types": 0,
  "ts/init-declarations": 0,
  "ts/max-params": 0,
  "ts/member-ordering": [2, { default: preset.tsMemberOrder }],
  "ts/method-signature-style": 2,
  "ts/naming-convention": 0,
  "ts/no-array-constructor": 2,
  "ts/no-array-delete": 2,
  "ts/no-base-to-string": 0,
  "ts/no-confusing-non-null-assertion": 0,
  "ts/no-confusing-void-expression": [2, { ignoreArrowShorthand: true, ignoreVoidOperator: false }],
  "ts/no-deprecated": 0,
  "ts/no-dupe-class-members": 2,
  "ts/no-duplicate-enum-values": 2,
  "ts/no-duplicate-type-constituents": 0,
  "ts/no-dynamic-delete": 0,
  "ts/no-empty-function": 0,
  "ts/no-empty-object-type": [2, { allowInterfaces: "with-single-extends" }],
  "ts/no-explicit-any": [2, { fixToUnknown: true, ignoreRestArgs: true }],
  "ts/no-extra-non-null-assertion": 0,
  "ts/no-extraneous-class": 0,
  "ts/no-floating-promises": 0,
  "ts/no-for-in-array": 0,
  "ts/no-implied-eval": 2,
  "ts/no-import-type-side-effects": 2,
  "ts/no-inferrable-types": [2, { ignoreParameters: false, ignoreProperties: true }],
  "ts/no-invalid-void-type": 2,
  "ts/no-loop-func": 0,
  "ts/no-magic-numbers": 0,
  "ts/no-meaningless-void-operator": 0,
  "ts/no-misused-new": 0,
  "ts/no-misused-promises": [2, { checksVoidReturn: false }],
  "ts/no-misused-spread": 2,
  "ts/no-mixed-enums": 0,
  "ts/no-namespace": [2, { allowDeclarations: true, allowDefinitionFiles: true }],
  "ts/no-non-null-asserted-nullish-coalescing": 2,
  "ts/no-non-null-asserted-optional-chain": 2,
  "ts/no-non-null-assertion": 0,
  "ts/no-redeclare": 2,
  "ts/no-redundant-type-constituents": 0,
  "ts/no-require-imports": 2,
  "ts/no-restricted-imports": 0,
  "ts/no-restricted-types": 0,
  "ts/no-shadow": 0,
  "ts/no-this-alias": [2, { allowDestructuring: true }],
  "ts/no-unnecessary-boolean-literal-compare": 0,
  "ts/no-unnecessary-condition": 0,
  "ts/no-unnecessary-parameter-property-assignment": 0,
  "ts/no-unnecessary-qualifier": 2,
  "ts/no-unnecessary-template-expression": 2,
  "ts/no-unnecessary-type-arguments": 0,
  "ts/no-unnecessary-type-assertion": 0,
  "ts/no-unnecessary-type-constraint": 2,
  "ts/no-unnecessary-type-parameters": 0,
  "ts/no-unsafe-argument": 0,
  "ts/no-unsafe-assignment": 0,
  "ts/no-unsafe-call": 0,
  "ts/no-unsafe-declaration-merging": 0,
  "ts/no-unsafe-enum-comparison": 0,
  "ts/no-unsafe-function-type": 2,
  "ts/no-unsafe-member-access": 0,
  "ts/no-unsafe-return": 0,
  "ts/no-unsafe-type-assertion": 0,
  "ts/no-unsafe-unary-minus": 2,
  "ts/no-unused-expressions": [2, { ignoreDirectives: true, allowShortCircuit: true }],
  "ts/no-unused-vars": [2, { vars: "local", args: "none", caughtErrors: "none", varsIgnorePattern: "^_", destructuredArrayIgnorePattern: "^_" }],
  "ts/no-use-before-define": [2, { functions: false, classes: false, variables: false, allowNamedExports: false }],
  "ts/no-useless-constructor": 0,
  "ts/no-useless-empty-export": 0,
  "ts/no-wrapper-object-types": 2,
  "ts/non-nullable-type-assertion-style": 0,
  "ts/only-throw-error": 0,
  "ts/parameter-properties": 0,
  "ts/prefer-as-const": 0,
  "ts/prefer-destructuring": 0,
  "ts/prefer-enum-initializers": 0,
  "ts/prefer-find": 2,
  "ts/prefer-for-of": 2,
  "ts/prefer-function-type": 2,
  "ts/prefer-includes": 0,
  "ts/prefer-literal-enum-member": 0,
  "ts/prefer-namespace-keyword": 2,
  "ts/prefer-nullish-coalescing": 0,
  "ts/prefer-optional-chain": 0,
  "ts/prefer-promise-reject-errors": 0,
  "ts/prefer-readonly": 0,
  "ts/prefer-readonly-parameter-types": 0,
  "ts/prefer-reduce-type-parameter": 0,
  "ts/prefer-regexp-exec": 0,
  "ts/prefer-return-this-type": 0,
  "ts/prefer-string-starts-ends-with": 0,
  "ts/promise-function-async": 0,
  "ts/related-getter-setter-pairs": 2,
  "ts/require-array-sort-compare": 0,
  "ts/require-await": 0,
  "ts/restrict-plus-operands": 0,
  "ts/restrict-template-expressions": 0,
  "ts/return-await": 0,
  "ts/strict-boolean-expressions": 0,
  "ts/switch-exhaustiveness-check": 0,
  "ts/triple-slash-reference": [2, { path: "never", types: "always", lib: "always" }],
  "ts/typedef": [2, { arrayDestructuring: false, arrowParameter: false, memberVariableDeclaration: false, objectDestructuring: false, parameter: false, propertyDeclaration: true, variableDeclaration: false }],
  "ts/unbound-method": 0,
  "ts/unified-signatures": 0,
  "ts/use-unknown-in-catch-callback-variable": 0,
};
