import preset from "./preset.js";

export default {
  "stylistic/array-bracket-newline": [2, "consistent"],
  "stylistic/array-bracket-spacing": 2,
  "stylistic/array-element-newline": [2, "consistent"],
  "stylistic/arrow-parens": 2,
  "stylistic/arrow-spacing": 2,
  "stylistic/block-spacing": 2,
  "stylistic/brace-style": 2,
  "stylistic/comma-dangle": [2, "always-multiline"],
  "stylistic/comma-spacing": 2,
  "stylistic/comma-style": 2,
  "stylistic/computed-property-spacing": 2,
  "stylistic/curly-newline": 2,
  "stylistic/dot-location": 0,
  "stylistic/eol-last": 2,
  "stylistic/function-call-argument-newline": [2, "consistent"],
  "stylistic/function-call-spacing": 2,
  "stylistic/function-paren-newline": [2, "multiline-arguments"],
  "stylistic/generator-star-spacing": 2,
  "stylistic/implicit-arrow-linebreak": 2,
  "stylistic/indent": [2, preset.indent],
  "stylistic/indent-binary-ops": [2, preset.indent],
  "stylistic/jsx-child-element-spacing": 0,
  "stylistic/jsx-closing-bracket-location": 2,
  "stylistic/jsx-closing-tag-location": 2,
  "stylistic/jsx-curly-brace-presence": 2,
  "stylistic/jsx-curly-newline": 2,
  "stylistic/jsx-curly-spacing": 2,
  "stylistic/jsx-equals-spacing": 2,
  "stylistic/jsx-first-prop-new-line": 2,
  "stylistic/jsx-function-call-newline": 2,
  "stylistic/jsx-indent-props": [2, preset.indent],
  "stylistic/jsx-max-props-per-line": 2,
  "stylistic/jsx-newline": 0,
  "stylistic/jsx-one-expression-per-line": [2, { allow: "single-child" }],
  "stylistic/jsx-pascal-case": [2, { allowNamespace: true }],
  "stylistic/jsx-quotes": 2,
  "stylistic/jsx-self-closing-comp": 2,
  "stylistic/jsx-sort-props": 0,
  "stylistic/jsx-tag-spacing": [2, { beforeClosing: "never" }],
  "stylistic/jsx-wrap-multilines": [
    2,
    {
      declaration: "parens-new-line",
      assignment: "parens-new-line",
      return: "parens-new-line",
      arrow: "parens-new-line",
      condition: "parens-new-line",
      logical: "parens-new-line",
      prop: "ignore",
      propertyValue: "parens-new-line",
    },
  ],
  "stylistic/key-spacing": 2,
  "stylistic/keyword-spacing": 2,
  "stylistic/line-comment-position": 0,
  "stylistic/linebreak-style": 0,
  "stylistic/lines-around-comment": 0,
  "stylistic/lines-between-class-members": 0,
  "stylistic/max-len": 0,
  "stylistic/max-statements-per-line": 0,
  "stylistic/member-delimiter-style": 2,
  "stylistic/multiline-comment-style": 0,
  "stylistic/multiline-ternary": [2, "always-multiline"],
  "stylistic/new-parens": 2,
  "stylistic/newline-per-chained-call": 0,
  "stylistic/no-confusing-arrow": 0,
  "stylistic/no-extra-parens": 0,
  "stylistic/no-extra-semi": 2,
  "stylistic/no-floating-decimal": 2,
  "stylistic/no-mixed-operators": 0,
  "stylistic/no-mixed-spaces-and-tabs": 0,
  "stylistic/no-multi-spaces": 2,
  "stylistic/no-multiple-empty-lines": [2, { max: 2, maxEOF: 1, maxBOF: 0 }],
  "stylistic/no-tabs": 0,
  "stylistic/no-trailing-spaces": 2,
  "stylistic/no-whitespace-before-property": 2,
  "stylistic/nonblock-statement-body-position": 2,
  "stylistic/object-curly-newline": 2,
  "stylistic/object-curly-spacing": [2, "always"],
  "stylistic/object-property-newline": [2, { allowAllPropertiesOnSameLine: true }],
  "stylistic/one-var-declaration-per-line": 2,
  "stylistic/operator-linebreak": [2, "after", { overrides: { "?": "ignore", ":": "ignore", "|": "before" } }],
  "stylistic/padded-blocks": 0,
  "stylistic/padding-line-between-statements": [
    2,
    { blankLine: "always", prev: "*", next: "return" },
    { blankLine: "always", prev: "*", next: "default" },
    { blankLine: "always", prev: "directive", next: "*" },
    { blankLine: "any", prev: "directive", next: "directive" },
  ],
  "stylistic/quote-props": [2, "consistent-as-needed"],
  "stylistic/quotes": 2,
  "stylistic/rest-spread-spacing": 2,
  "stylistic/semi": 2,
  "stylistic/semi-spacing": 2,
  "stylistic/semi-style": 2,
  "stylistic/space-before-blocks": 2,
  "stylistic/space-before-function-paren": [2, { anonymous: "always", named: "never", asyncArrow: "always", catch: "always" }],
  "stylistic/space-in-parens": 2,
  "stylistic/space-infix-ops": 2,
  "stylistic/space-unary-ops": 2,
  "stylistic/spaced-comment": 2,
  "stylistic/switch-colon-spacing": 2,
  "stylistic/template-curly-spacing": 2,
  "stylistic/template-tag-spacing": 2,
  "stylistic/type-annotation-spacing": 2,
  "stylistic/type-generic-spacing": 2,
  "stylistic/type-named-tuple-spacing": 2,
  "stylistic/wrap-iife": 2,
  "stylistic/wrap-regex": 2,
  "stylistic/yield-star-spacing": 2,
};
